---
title: "Project 4: Data Collection & Wrangling"
format: html
---

Loading R packages
```{r}
library(rvest)
library(dplyr)
library(purrr)
library(tidyverse)
library(httr)
library(lubridate)
library(here)
library(jsonlite)

#OMDB API wrappers
library(imdbapi)
library(ROMDB)
```

Obtain list of American movies from Wikipedia from the years 2000 - 2025 
```{r}
#sample code for 1 year (2000)
html <- read_html(
  "https://en.wikipedia.org/wiki/List_of_American_films_of_2000"
)

results <- html %>%
  html_nodes(".wikitable") %>%
  .[-1] %>% #removes the first table because it is for the top highest grossing for the specific year
  html_table()

#combines the separate tables (months) into one data frame, and adds a column with the relevant year
film_2000 <- bind_rows(results) %>%
  mutate(year = 2000)

#URLs for wikipedia pages for American films 2000-2025
years <- 2000:2025

urls <- paste0(
  "https://en.wikipedia.org/wiki/List_of_American_films_of_",
  years
)

#Function to get all movies from 2000-2025
extract_wiki_movies <- function(url, year) {
  html <- read_html(url)

  results <- html %>%
    html_nodes(".wikitable") %>%
    .[-1] %>%
    html_table()

  bind_rows(results) %>%
    mutate(year = year)
}

#using purrr to apply the custom function for all urls and years specified
wiki_films <- map2_dfr(urls, years, extract_wiki_movies)

if (!dir.exists(here("data"))) {
  dir.create(here("data"))
}

#saving data
saveRDS(wiki_films, file = here("data", "wiki_films.RDS"))
wiki_films <- readRDS("data/wiki_films.RDS")
clean_wiki_films <- readRDS("data/clean_wiki_films.RDS")

```

Clean film_data 
```{r}
clean_wiki_films <- wiki_films %>%
  filter(!is.na(Title)) %>%
  mutate(
    release = mdy(paste(Opening...1, Opening...2, year))
  ) %>%
  rename("Month" = "Opening...1") %>%
  rename("Date" = "Opening...2") %>%
  select(
    -c(
      "...7",
      ".mw-parser-output .tooltip-dotted{border-bottom:1px dotted;cursor:help}Ref."
    )
  ) %>%
  filter(release < "2025-11-18")


saveRDS(clean_wiki_films, file = here("data", "clean_wiki_films.RDS"))

#Extracting the list of films
list_films <- clean_wiki_films %>%
  pull(Title)
```

Use "IMDBAPI" Wrapper (which actually calls the OMDB API, not the IMDB API)
```{r}
#trial code with a list of 20 films

trial <- list_films[1:20]

test <- map_dfr(
    trial,
    ~ find_by_title(
      .x,
      type = "movie",
      season = NULL,
      episode = NULL,
      year_of_release = NULL,
      plot = "short",
      include_tomatoes = FALSE,
      api_key = omdb_api_key()
    )
  )


#de-duplicates entries
test <- test %>%
  distinct(imdbID, .keep_all = TRUE)
```

```{r}
trial <- list_films[1:20]

test <- map_dfr(
    trial,
    ~ find_by_title(
      .x,
      type = "movie",
      season = NULL,
      episode = NULL,
      year_of_release = NULL,
      plot = "short",
      include_tomatoes = FALSE,
      api_key = omdb_api_key()
    )
  )


#de-duplicates entries
test <- test %>%
  distinct(imdbID, .keep_all = TRUE)
```

```{r}
trial_2 <- list_films[21:100]

test_2 <- map_dfr(
    trial_2,
    ~ find_by_title(
      .x,
      type = "movie",
      season = NULL,
      episode = NULL,
      year_of_release = NULL,
      plot = "short",
      include_tomatoes = FALSE,
      api_key = omdb_api_key()
    )
  )


#de-duplicates entries
test_2 <- test_2 %>%
  distinct(imdbID, .keep_all = TRUE)
```


```{r}
#splitting list_films into separate smaller lists to run the API
split_list <- function(x, chunk_size) {
  split(x, ceiling(seq_along(x) / chunk_size))
}

list_sep <- split_list(list_films, 950)

#getting separate lists
imap(list_sep, ~ assign(paste0("list_", .y), .x, envir = .GlobalEnv))


#function
data_2 <- 
  map_dfr(
    list_2,
    ~ find_by_title(
      .x,
      type = "movie",
      season = NULL,
      episode = NULL,
      year_of_release = NULL,
      plot = "short",
      include_tomatoes = TRUE,
      api_key = omdb_api_key()
    )
  )

data_2 <- data_2 %>% 
  distinct(imdbID, .keep_all = TRUE)

saveRDS(data_2, file = here("data", "data_1.RDS"))
```


```{r}
https://api.themoviedb.org/3/search/movie

tmdb_search <- function(title, api_key) {
  
  url <- "https://api.themoviedb.org/3/search/movie"
  res <- GET(
    url,
    query = list(
      api_key = api_key,
      query   = title
    )
  )
  data <- content(res, as = "text", encoding = "UTF-8") |> 
    fromJSON()
  
  as_tibble(data$results)
}

movie_results <- map_dfr(
  list_1,
  ~ tmdb_search(.x, api_key = tmdb_key)
)


```
